# Generated by Django 4.2.23 on 2025-07-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_placeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeimage',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
