# Generated by Django 5.2.4 on 2025-07-09 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_placeimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeimage',
            name='number',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Позиция'),
        ),
    ]
