# Generated by Django 4.2.3 on 2025-07-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_place_options_alter_placeimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeimage',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Позиция'),
        ),
    ]
