# Generated by Django 5.2.4 on 2025-07-15 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_placeimage_places_plac_number_a294f0_idx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='description_long',
            new_name='long_description',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='description_short',
            new_name='short_description',
        ),
    ]
